server:
  port: 8081

spring:
  application:
    name: pdf-extractor
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Tesseract OCR configuration
tesseract:
  datapath: /usr/local/share/tessdata
  language: eng
  pagesegmode: 6

# OpenAI translation service configuration
open-ai:
  chat-model:
    api-key:
    model: gpt-4o-mini
    api-url: https://api.openai.com/v1/chat/completions
